package metroapp.checkarrival;
import java.awt.Color;
import metroapp.Repository;
import Images.TransicionGUI;
import java.util.ArrayList;
import metroapp.Time;
import metroapp.file.MetroAppFile;
import metroapp.main.MetroApp;
import static metroapp.main.MetroApp.*;

public class CheckArrivalGUI extends javax.swing.JFrame {
    private static Repository myRepository = MetroAppFile.myRepository;
    public static Time time;
    
    public static int delay; 
    
    private String selected = "";

    protected static Time t1;
    protected static Time t2;
    protected static Time t3;
    protected static Time t4;
    protected static Time t5;

    protected static ArrayList<Time> times1 = new ArrayList<Time>();
    protected static ArrayList<Time> times2 = new ArrayList<Time>();
    protected static ArrayList<Time> times3 = new ArrayList<Time>();
    protected static ArrayList<Time> times4 = new ArrayList<Time>();
    protected static ArrayList<Time> times5 = new ArrayList<Time>();
    protected static ArrayList<Time> times6 = new ArrayList<Time>();
    protected static ArrayList<Time> times7 = new ArrayList<Time>();
    protected static ArrayList<Time> times8 = new ArrayList<Time>();
    protected static ArrayList<Time> times9 = new ArrayList<Time>();
    protected static ArrayList<Time> times10 = new ArrayList<Time>();
    
    
    
    /**
     * Creates new form CheckArrivalGUI
     */
    public CheckArrivalGUI() {
        initComponents();
        setTitle("MetroApp - Check Arrival");
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        getContentPane().setBackground(new Color(253, 249, 210));
        setSize(786, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select station:");

        jTextArea1.setBackground(new java.awt.Color(255, 186, 149));
        jTextArea1.setColumns(20);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 3));
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ARRIVAL.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("ARRIVALS");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abbey Wood", "Angel Road", "Greenwich", "Kingswood", "Oxford", "Queen's Park", "St. Pancras", "Victoria", "St. Waterloo", "Windsor" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(127, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TransicionGUI().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String result = "";
        selected = jComboBox1.getSelectedItem().toString();  
        if (selected.equals("Abbey Wood")) {
            delay = 0;
            time = new Time(l1, "08:45 09:45 10:45 11:45 12:45 13:45 14:45 "
                    + "15:45 16:45 17:45 18:45 19:45 20:45", delay);
            s1.setTime(time);
            result += "\n            " +s1.getTime() + "\n";
            s1.removeTime();
           
            delay = 0;
            time = new Time(l4, "13:05 13:10 13:15 14:05 14:10 "
                    + "14:15 15:05 15:10 15:15 16:05 16:10 "
                    + "16:15 17:05 17:10 17:15 18:05 18:10 "
                    + "18:15 19:05 19:10 19:15 20:05 20:10 "
                    + "20:15 21:05 21:10 21:15 22:05 22:10 "
                    + "22:15 23:05 23:15", delay);
            s1.setTime(time);
            result += "            "+ s1.getTime() + "\n";
            s1.removeTime();
            
            delay = 0;
            time = new Time(l5, "07:00 07:10 07:20 07:30 07:40 07:50 08:00 "
                     + "08:10 08:20 08:30 08:40 08:50 09:00 09:10 09:20 09:30 "
                     + "09:40 09:50 10:00 10:10 10:20 10:30 10:40 10:50 11:00 "
                     + "11:10 11:20 11:30 11:40 11:50 12:00 12:10 12:20 12:30 "
                     + "12:40 12:50 13:00 13:10 13:20 13:30 13:40 13:50 14:00", delay);
            s1.setTime(time);
            result += "            "+ s1.getTime() + "\n";
            s1.removeTime();
            
            jTextArea1.setText("\n" + result);
           
            
        } else if (selected.equals("Angel Road")) {
             delay = 0;
             time = new Time(l2, "07:00 07:10 07:20 07:30 07:40 07:50 08:00 "
                     + "08:10 08:20 08:30 08:40 08:50 09:00 09:10 09:20 09:30 "
                     + "09:40 09:50 10:00 10:10 10:20 10:30 10:40 10:50 11:00 "
                     + "11:10 11:20 11:30 11:40 11:50 12:00 12:10 12:20 12:30 "
                     + "12:40 12:50 13:00 13:10 13:20 13:30 13:40 13:50 14:00", delay);
            s2.setTime(time);
            result += "\n            "+ s2.getTime() + "\n";
            s2.removeTime();
            
            delay = 0;
            time = new Time(l3, "06:55 07:10 07:55 08:10 08:55 09:10 09:55 "
                    + "10:10 10:55 11:10 11:55 12:10 12:55 13:10 13:55 "
                    + "14:00 14:55 15:00 15:55 16:10 16:55 17:10 17:55 "
                    + "18:10 18:55 19:10 19:55 20:10", delay);
            s2.setTime(time);
            result += "            "+s2.getTime() + "\n";
            s2.removeTime();
            
            delay = 0;
            time = new Time(l4, "08:45 09:45 10:45 11:45 12:45 13:45 14:45 "
                    + "15:45 16:45 17:45 18:45 19:45 20:45", delay);
            s2.setTime(time);
            result += "            "+s2.getTime() + "\n";
            s2.removeTime();
            
            jTextArea1.setText("\n" + result);
            result = "";
            
        } else if (selected.equals("Greenwich")) {
            delay = 0;
             time = new Time(l1, "08:55 09:55 10:55 11:55 12:55 13:55 14:55 "
                    + "15:55 16:55 17:55 18:55 19:55 20:55", delay);
            s3.setTime(time);
            result += "\n            "+s3.getTime() + "\n";
            s3.removeTime();
            
            delay = 0;
            time = new Time(l2, "15:20 15:50 16:20 16:50 17:20 17:50 18:20 "
                    + "18:50 19:20 19:50 20:20 20:50 21:20 21:50", delay);
            s3.setTime(time);
            result += "            "+s3.getTime() + "\n";
            s3.removeTime();
            
            delay = 0;
            time = new Time(l3, "06:40 06:55 07:45 07:55 08:40 08:55 09:40 "
                    + "09:55 10:40 10:55 11:40 11:55 12:40 12:55 13:40 "
                    + "13:55 14:40 14:55 15:40 15:55 16:40 16:55 17:40 "
                    + "17:55 18:40 18:55 19:40 19:55", delay);
            s3.setTime(time);
            result += "            "+s3.getTime() + "\n";
            s3.removeTime();
            
            jTextArea1.setText("\n" + result);
            result = "";
            
        } else if (selected.equals("Kingswood")) {
            delay = 0;
            time = new Time(l1, "09:00 10:00 11:00 12:00 13:00 14:00 15:00 "
                    + "16:00 17:00 18:00 19:00 20:00 21:00", delay);
            s4.setTime(time);
            result += "\n            "+s4.getTime() + "\n";
            s4.removeTime();
            
            delay = 0;
            time = new Time(l3, "07:00 07:15 08:00 08:15 09:00 09:15 10:00 "
                    + "10:15 11:00 11:15 12:00 12:15 13:00 13:15 14:00 "
                    + "14:15 15:00 15:15 16:00 16:15 17:00 17:15 18:00 "
                    + "18:15 19:00 19:15 20:00 20:15", delay);
            s4.setTime(time);
            result += "            "+s4.getTime() + "\n";
            s4.removeTime();
            
            delay = 0;
            time = new Time(l4,"12:50 12:55 13:00 13:50 13:55 14:00 14:50 "
                    + "14:55 15:00 15:50 15:55 16:00 16:50 16:55 17:00 17:50 "
                    + "17:55 18:00 18:50 18:55 19:00 19:50 19:55 20:00 20:50 "
                    + "20:55 21:00 21:50 21:55 22:00 22:50 22:55 23:00", delay);
            s4.setTime(time);
            result += "            "+s4.getTime() + "\n";
            s4.removeTime();
            
            jTextArea1.setText("\n" + result);
            
            
        } else if (selected.equals("Oxford")) {
            delay = 0;
            time = new Time(l1, "09:15 10:15 11:15 12:15 13:15 14:15 15:15 "
                    + "16:15 17:15 18:15 19:15 20:15 21:15", delay);
            s10.setTime(time);
            result += "\n            "+s10.getTime() + "\n";
            s10.removeTime();
            
            delay = 0;
            time = new Time(l4,"15:35 15:40 15:45 16:35 16:40 "
                    + "16:45 17:35 17:40 17:45 18:35 18:40 "
                    + "18:45 19:35 19:40 19:45 20:35 20:40 "
                    + "20:45 21:35 21:40 21:45 22:35 22:40 "
                    + "22:45 23:35 23:40 23:45 00:35 00:40 "
                    + "00:45 01:35 01:40 01:45", delay);
            s10.setTime(time);
            result += "            "+s10.getTime() + "\n";
            s10.removeTime();
            
            delay = 0;
            time = new Time(l5,"17:00 18:00 19:00 20:00 21:00 22:00 23:00", delay);
            s10.setTime(time);
            result += "            "+s10.getTime() + "\n";
            s10.removeTime();
            
            jTextArea1.setText("\n" + result);
           
            
            
        } else if (selected.equals("Queen's Park")) {
            
            delay = 0;
            time = new Time(l2,"07:20 07:30 07:40 07:50 08:00 08:10 08:30 "
                    + "08:50 09:10 09:30 09:50 10:10 10:30 10:50 "
                    + "11:10 11:30 11:50 12:10 12:30 12:50 13:10 13:30 "
                    + "13:50 14:10 14:30 14:50 15:10 15:30 15:50 14:10", delay);
            s5.setTime(time);
            result += "\n            "+s5.getTime() + "\n";
            s5.removeTime();
            
            delay = 0;
            time = new Time(l4, "13:35 13:40 13:45 14:35 14:40 "
                    + "14:45 15:35 15:40 15:45 16:35 16:40 "
                    + "16:45 17:35 17:40 17:45 18:35 18:40 "
                    + "18:45 19:35 19:40 19:45 20:35 20:40 "
                    + "20:45 21:35 21:40 21:45 22:35 22:40 "
                    + "22:45 23:35 23:40 23:45", delay);
            s5.setTime(time);
            result += "            "+s5.getTime() + "\n";
            s5.removeTime();
            
            delay = 0;
            time = new Time(l5, "15:40 16:40 17:50 18:40 19:40 20:40 21:40", delay);
            s5.setTime(time);
            result += "            "+s5.getTime() + "\n";
            s5.removeTime();
            
            jTextArea1.setText("\n" + result);
            
            
            
        } else if (selected.equals("St. Pancras")) {
            
            delay = 0;
            time = new Time(l1, "09:35 10:35 11:35 12:35 13:35 14:35 15:35 "
                    + "16:35 17:35 18:35 19:35 20:35 21:35", delay);
            s9.setTime(time);
            result += "\n            "+s9.getTime() + "\n";
            s9.removeTime();
            
            delay = 0;
            time = new Time(l3,  "07:30 07:45 08:30 08:45 09:30 09:45 10:30 "
                    + "10:45 11:30 11:45 12:30 12:45 13:30 13:45 14:30 "
                    + "14:45 15:30 15:45 16:30 16:45 17:30 17:45 18:30 "
                    + "18:45 19:30 19:45 20:30 20:45", delay);
            s9.setTime(time);
            result += "            "+s9.getTime() + "\n";
            s9.removeTime();
            
            delay = 0;
            time = new Time(l5,"16:30 17:30 18:30 19:30 20:30 21:30 22:30", delay);
            s9.setTime(time);
            result += "            "+s9.getTime() + "\n";
            s9.removeTime();
            
            jTextArea1.setText("\n" + result);
            result = "";
            
            
        } else if (selected.equals("Victoria")) {              
            delay = 0;
            time = new Time(l1, "07:25 07:35 07:45 07:55 08:05 08:15 08:35 "
                    + "08:55 09:15 09:35 09:55 10:15 10:35 10:55 "
                    + "11:15 11:35 11:55 12:15 12:35 12:55 13:15 13:35 "
                    + "13:55 14:15 14:35 14:55 15:15 15:35 15:55 14:15", delay);
            s7.setTime(time);
            result += "\n            "+s7.getTime() + "\n";
            s7.removeTime();
            
            time = new Time(l2, "08:45 09:45 10:45 11:45 12:45 13:45 14:45 "
                    + "15:45 16:45 17:45 18:45 19:45 20:45", delay);
            s7.setTime(time);
            result += "            "+s7.getTime() + "\n";
            s7.removeTime();
            
            time = new Time(l3, "12:45 12:50 12:55 13:00 13:50 13:55 14:00 14:50 "
                    + "14:55 15:00 15:50 15:55 16:00 16:50 16:55 17:00 17:50 "
                    + "17:55 18:00 18:50 18:55 19:00 19:50 19:55 20:00 20:50 "
                    + "20:55 21:00 21:50 21:55 22:00 22:50 22:55 23:00", delay);
            s7.setTime(time);
            result += "            "+s7.getTime() + "\n";
            s7.removeTime();
            
            jTextArea1.setText("\n" + result);
            result = "";
            
            
        } else if (selected.equals("Waterloo")) {
            delay = 0;
            time = new Time(l2,"07:35 07:45 07:55 08:05 08:15 08:35 08:55 "
                    + "09:05 09:15 09:35 09:55 10:05 10:15 10:35 "
                    + "10:55 11:05 11:15 11:35 11:55 12:05 12:15 12:35 "
                    + "12:55 13:05 13:15 13:35 13:55 14:05 14:15 14:35", delay);
            s6.setTime(time);
            result += "\n            "+s6.getTime() + "\n";
            s6.removeTime();
            
            time = new Time(l3, "08:00 08:15 09:00 09:15 10:00 10:15 11:00 "
                    + "11:15 12:00 12:15 13:00 13:15 14:00 14:15 15:00 "
                    + "15:15 16:00 16:15 17:00 16:15 18:00 18:15 19:00 "
                    + "19:15 20:00 20:15 21:00 21:15", delay);
            s6.setTime(time);
            result += "            "+s6.getTime() + "\n";
            s6.removeTime();
            
            time = new Time(l5,"16:00 17:00 18:00 19:00 20:00 21:00 22:00", delay);
            s6.setTime(time);
            result += "            "+s6.getTime() + "\n";
            s6.removeTime();
            
            jTextArea1.setText("\n" + result);
            result = "";
            
            
        } else if (selected.equals("Windsor")) {
            delay = 0;
            time = new Time(l2, "07:40 07:50 08:00 08:10 08:20 08:40 09:00 "
                    + "09:10 09:20 09:40 10:00 10:10 10:20 10:40 "
                    + "11:00 11:10 11:20 11:40 12:00 12:10 12:20 12:40 "
                    + "13:00 13:10 13:20 13:40 14:00 14:10 14:20 14:40", delay);
            s8.setTime(time);
            result += "\n            "+s8.getTime() + "\n";
            s8.removeTime();
            
            delay = 0;
            time = new Time(l4,  "14:05 14:10 14:15 15:05 15:10 "
                    + "15:15 16:05 16:10 16:15 17:05 17:10 "
                    + "17:15 18:05 18:10 18:15 19:05 19:10 "
                    + "19:15 20:05 20:10 20:15 21:05 21:10 "
                    + "21:15 22:05 22:10 22:15 23:05 23:10 "
                    + "23:15 00:05 00:10 00:15", delay);
            s8.setTime(time);
            result += "            "+s8.getTime() + "\n";
            s8.removeTime();
            
            delay = 0;
            time = new Time(l5, "16:10 17:10 18:10 19:10 20:10 21:10 22:10", delay);
            s8.setTime(time);
            result += "            "+s8.getTime() + "\n";
            s8.removeTime();
            
            jTextArea1.setText("\n" + result);
            result += "";
            
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}